<?php

namespace jackwhitworth\hooks;

// Removes the HTML indicator that's wrapped around the SEO HTML output.
\add_filter( 'the_seo_framework_indicator', '__return_false' );

// Removes "Generated by The SEO Framework" from the Sitemap output.
\add_filter( 'the_seo_framework_indicator_sitemap', '__return_false' );
